"""
Keep PDF code visually distinct and preserve the literal evidence inside each block.
"""

import base64
import re
import zlib
from pathlib import Path

import pytest

from hypothesis_helm.reporting.reports.links import linked_prose
from hypothesis_helm.reporting.reports.pdf import write_pdf


def _streams(path: Path) -> bytes:
    """
    Decode PDF drawing commands without adding a PDF reader to the test dependencies.

    Args:
        path (Path): ReportLab PDF generated by the test.

    Returns:
        bytes: Drawing commands from every compressed page stream.
    """
    streams = []
    for body in re.findall(rb"\d+ 0 obj\s*(.*?)\s*endobj", path.read_bytes(), re.DOTALL):
        if b"/Subtype /Image" in body:
            continue
        if b"/Filter [ /ASCII85Decode /FlateDecode ]" in body and (match := re.search(rb"stream\s*\n(.*?)endstream", body, re.DOTALL)):
            streams.append(zlib.decompress(base64.a85decode(match[1].strip(), adobe=True)))
    return b"\n".join(streams)


@pytest.mark.parametrize("fence,closed", [("```", True), ("````", True), ("~~~", True), ("```", False)])
def test_pdf_shades_literal_blocks(tmp_path: Path, fence: str, closed: bool) -> None:
    """
    Shade fenced code without treating YAML comments, links, or markup as document structure.

    Args:
        tmp_path (Path): PDF output directory.
        fence (str): Supported opening delimiter.
        closed (bool): Whether the block has an explicit closing delimiter.

    Returns:
        None: The PDF contains literal indented evidence, a gray background, and no code-created links.
    """
    code = 'spec:\n    name: "<pre> & **literal**"\n\n# Not a heading\n[literal](https://example.com/code)'
    if fence == "````":
        code += "\n```"
    content = f"# Test\n\n## Evidence\n\n{fence}yaml\n{code}" + (f"\n{fence}\n" if closed else "")
    pdf = tmp_path / "code.pdf"
    write_pdf(content, pdf)
    drawn = _streams(pdf)
    # This is a filled box, not a monospace-only simulation of a code block.
    assert b".945098 .952941 .960784 rg" in drawn
    assert b'(    name: "<pre> & **literal**")' in drawn
    assert b"(# Not a heading)" in drawn
    assert b"/Title (Not a heading)" not in pdf.read_bytes()
    assert b"/URI (https://example.com/code)" not in pdf.read_bytes()
    assert b"/BaseFont /Courier" in pdf.read_bytes()


def test_long_code_blocks_wrap_and_continue(tmp_path: Path) -> None:
    """
    Preserve all long literals and blank lines when code crosses report pages.

    Args:
        tmp_path (Path): PDF output directory.

    Returns:
        None: Every code line survives wrapping and each continuation page has its own background.
    """
    pdf = tmp_path / "long-code.pdf"
    records = [f"    entry-{index:03d}: value" for index in range(130)]
    records.insert(1, "")
    records.insert(2, "x" * 250)
    records.insert(3, "\u03bb" * 25)
    write_pdf("# Test\n\n## Evidence\n\n```yaml\n" + "\n".join(records) + "\n```", pdf)
    drawn = _streams(pdf)
    for index in range(130):
        assert f"(    entry-{index:03d}: value)".encode() in drawn
    assert drawn.count(b".945098 .952941 .960784 rg") >= 3
    assert b"(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" in drawn
    assert b"x" * 250 not in drawn
    assert re.search(rb"BT 1 0 0 1 44 \d+ Tm\s+T\* ET", drawn)
    # Unicode escapes are included in the wrap width, rather than overflowing it.
    assert b"\\\\u03bb" in drawn
    assert b"\\\\u03bb" * 25 not in drawn


def test_inline_code_and_links_have_distinct_markup(tmp_path: Path) -> None:
    """
    Highlight inline evidence while keeping real links clickable and literal Markdown inert.

    Args:
        tmp_path (Path): PDF output directory.

    Returns:
        None: Inline code is escaped and shaded; only the prose link has a PDF URI action.
    """
    line = '**Input:** ``$.name = "<pre> & [literal](https://example.com/code) **x** ` a  b"``; [Guide](https://example.com/guide)'
    markup = linked_prose(line)
    assert '<font name="Courier" backColor="#f1f3f5">' in markup
    assert "&lt;pre&gt;" in markup and "&amp;" in markup
    assert "<b>Input:</b>" in markup and "**x**" in markup
    assert "a&#160;&#160;b" in markup
    assert markup.count("<link ") == 1
    pdf = tmp_path / "inline.pdf"
    write_pdf("# Test\n\n## Evidence\n\n" + line, pdf)
    assert b".945098 .952941 .960784 rg" in _streams(pdf)
    assert b"/URI (https://example.com/guide)" in pdf.read_bytes()
    assert b"/URI (https://example.com/code)" not in pdf.read_bytes()
