apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  visible: {{ .Values.visible | quote }}
  hidden: {{ .Values.secretSwitch | default "fallback" | quote }}
  indexed: {{ index .Values "other-switch" | default "off" | quote }}
